const dates = {
    'Day 1 - Arrival & Kyoto': {
        date: '2025-01-09',
        schedule: [
            {
                title: '落機 & 入境',
                time: '0715',
                description: '',
                openingTime: '',
                fee: '',
            },
            {
                title: 'Transist',
                time: '',
                description: 'HARUKA -> 京都 (¥2200) 80MINS\n去酒店放行李 + 食嘢(?)',
                openingTime: '',
                fee: '',
            },
            {
                title: '金閣寺',
                time: '',
                description: 'JR京都站往"圓町站"\n204/205巴士往"金閣寺道停靠站"落車',
                openingTime: '0900-1700',
                fee: '500',
            },
            {
                title: '二條城',
                time: '',
                description: '204/12 巴士"堀川丸太町"落車',
                openingTime: '0845-1700',
                fee: '1050',
            },
            {
                title: '北野天滿宮',
                time: '',
                description: '由金閣寺行過去~15分鐘',
                openingTime: '',
                fee: 'FREE',
            },
            {
                title: '京都塔',
                time: '',
                description: '北野天滿宮出發: 50巴士 "下京區總合廳舍前（下京區公所）"落車\n二條城出發: JR京都站落車',
                openingTime: '1000-2100',
                fee: '900',
            },
            {
                title: '鴨川 (OPTIONAL)',
                time: '',
                description: 'Chill place',
                openingTime: '',
                fee: '',
            },
            {
                title: '買日用品',
                time: '',
                description: 'Rest early',
                openingTime: '',
                fee: '',
            },
        ],
    },
    'Day 2 - Kyoto': {
        date: '2025-01-10',
        schedule: [
            {
                title: '早起 & Check Out',
                time: '550起身~630出門',
                description: '��李放酒店',
                openingTime: '',
                fee: '',
            },
            {
                title: 'Transit 去清水寺',
                time: '',
                description: '206巴士（清水道落車）\nOR 電車 "D奈良線" > "京阪本線" > "清水五条站"',
                openingTime: '',
                fee: '400',
            },
            {
                title: '二年坂->三年坂',
                time: '',
                description: '行路',
                openingTime: '',
                fee: '',
            },
            {
                title: '仁王門->清水寺',
                time: '',
                description: '',
                openingTime: '0600-1800',
                fee: '400',
            },
            {
                title: '八坂神社->花見小路->錦市場',
                time: '',
                description: '行路',
                openingTime: '',
                fee: '',
            },
            {
                title: '四條車站',
                time: '',
                description: 'Pokemon Center\n行街',
                openingTime: '',
                fee: '',
            },
            {
                title: '伏見稻荷大社 (OPTIONAL)',
                time: '',
                description: '',
                openingTime: '',
                fee: '',
            },
            {
                title: 'Transit 去梅田',
                time: '',
                description: 'JR 京都站 > JR 大阪站',
                openingTime: '',
                fee: '',
            },
        ],
    },
    'Day 3 - 梅田 (May swap with D4)': {
        date: '2025-01-11',
        schedule: [
            {
                title: 'PLEASE NOTE: 今日行程除"展望台"外無先後之分',
                time: '',
                description: '',
                openingTime: '',
                fee: '',
            },
            {
                title: 'GRAND FRONT',
                time: '',
                description: '',
                openingTime: '1100-2100',
                fee: '',
            },
            {
                title: '阪急百貨店梅田總店',
                time: '',
                description: '',
                openingTime: '1000-2100',
                fee: '',
            },
            {
                title: 'HEP FIVE',
                time: '',
                description: '',
                openingTime: '1100-2100',
                fee: '',
            },
            {
                title: 'LINKS UMEDA',
                time: '',
                description: '',
                openingTime: '1000-2100',
                fee: '',
            },
            {
                title: '大丸百貨店梅田店',
                time: '',
                description: '',
                openingTime: '1000-2000',
                fee: '',
            },
            {
                title: '阪神百貨店梅田本店',
                time: '',
                description: '',
                openingTime: '1000-2130',
                fee: '',
            },
            {
                title: '梅田藍天大廈',
                time: '',
                description: '',
                openingTime: '1000-2000',
                fee: '',
            },
            {
                title: '藍天大廈展望台',
                time: '',
                description: 'KLOOK即日購票 -> 3/F 搭Lift到 39/F\n可到上一層的Cafe & Shop\n再行上到露天平台',
                openingTime: '930-2230 **最後入場2200**',
                fee: '2000',
            },
        ],
    },
    'Day 4 - 奈良 (May swap with D3)': {
        date: '2025-01-12 Sunday',
        schedule: [
            {
                title: 'Transit 去奈良',
                time: '45 Mins',
                description: '近鐵奈良站',
                openingTime: '',
                fee: '820',
            },
            {
                title: '奈良公園',
                time: '',
                description: '',
                openingTime: '',
                fee: '',
            },
            {
                title: '東大寺',
                time: '',
                description: '',
                openingTime: '',
                fee: '',
            },
            {
                title: '若草山',
                time: '',
                description: '',
                openingTime: '',
                fee: '',
            },
        ],
    },
    'Day 5 - 天王寺': {
        date: '2025-01-13',
        schedule: [
            {
                title: '通天閣',
                time: '',
                description: '睇情況決定上唔上',
                openingTime: '最後入場1930',
                fee: '展望台 900 | 戶外展望台 1200 | 滑梯 1000',
            },
            {
                title: '天王寺公園',
                time: '',
                description: '',
                openingTime: '',
                fee: '150 For 慶澤園',
            },
            {
                title: '四天王寺',
                time: '',
                description: '',
                openingTime: '參拜 0830-1600',
                fee: '',
            },
            {
                title: 'HARUKAS 300',
                time: '',
                description: '黃昏/夜景',
                openingTime: '最後入場2130',
                fee: '2000 / KLOOK: HKD $80',
            },
        ],
    },
    'Day 6 - 姬路': {
        date: '2025-01-14 Tuesday',
        schedule: [
            {
                title: 'Transit',
                time: '5MINS + 30MINS',
                description: 'JR大阪 -> 新大阪 -> 姬路\nhttps://www.klook.com/zh-HK/rails-32/1012-japan/search/?date_range_count=90&origin_position_name=%E6%96%B0%E5%A4%A7%E9%98%AA&origin_position=37bb8b76-2136-4a2b-96a8-2f35df71fd20&destination_position_name=%E5%A7%AB%E8%B7%AF&destination_position=39a9f496-1cc9-445b-9a09-b1961ad6879d&departure_date=2025-01-14&passengers=%5B%5D&product_type=jprail',
                openingTime: '',
                fee: '新幹線: HKD $166',
            },
            {
                title: '姬路城',
                time: '',
                description: '',
                openingTime: '900-1700',
                fee: '1000',
            },
            {
                title: 'Transit 去神戶',
                time: '',
                description: 'JR姬路 -> JR神戶',
                openingTime: '',
                fee: '',
            },
            {
                title: '臨海樂園',
                time: '',
                description: '',
                openingTime: '',
                fee: '',
            },
            {
                title: '阿美利堅公園',
                time: '',
                description: '',
                openingTime: '',
                fee: '',
            },
            {
                title: 'DINNER',
                time: '',
                description: '',
                openingTime: '',
                fee: '',
            },
            {
                title: 'Transit 去梅田',
                time: '30 MINS',
                description: 'JR新快速 OR 阪急電鐵',
                openingTime: '',
                fee: '400',
            },
        ],
    },
    'Day 7 - 大阪城 & 難波': {
        date: '2025-01-10',
        schedule: [
            {
                title: '大阪城天守閣',
                time: '',
                description: '大阪城公園免費入院',
                openingTime: '900-1700',
                fee: '600',
            },
            {
                title: '日本橋',
                time: '',
                description: '',
                openingTime: '',
                fee: '',
            },
            {
                title: '心齋橋 + 道頓堀',
                time: '',
                description: '',
                openingTime: '',
                fee: '',
            },
            {
                title: 'Pokemon Center Osaka DX',
                time: '',
                description: 'DAIMARU SHINSAIBASHI 本館9樓',
                openingTime: '',
                fee: '',
            },
        ],
    },
    'Day 8 - LAST DAY': {
        date: '2025-01-10',
        schedule: [
            {
                title: '梅田行街',
                time: '',
                description: '',
                openingTime: '',
                fee: '',
            },
            {
                title: 'Transit 去機場',
                time: '1600',
                description: '搭HARUKA, 車程 45 MINS',
                openingTime: '',
                fee: '',
            },
            {
                title: '出境 & Flight to HK',
                time: '2010-2340',
                description: '',
                openingTime: '',
                fee: '',
            },
        ],
    },
};

export default dates;
